config/urls.py
from django.contrib import admin
from django.urls    import path, include
from django.conf    import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home")
]

users/urls.py
from django.urls import path

from users.views import LoginView, log_out, SignUpView, github_login, github_callback, kakao_login, kakao_callback, complete_verification

app_name = "users"

urlpatterns = [
    path("login", LoginView.as_view(), name="login"),
    path("login/github", github_login, name="github-login"),
    path("login/github/callback", github_callback, name="github-callback"),
    path("login/kakao", kakao_login, name="kakao-login"),
    path("login/kakao/callback", kakao_callback, name="kakao-callback"),
    path("logout", log_out, name="logout"),
    path("signup", SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", complete_verification, name="complete-verification")
]

templates/partials/footer.html
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-600">
    &copy; 2019 MyAirbnb, Inc. All rights reserved. Contact me via jcs191072@gmail.com
</footer>

templates/partials/header.html
<header>
    <a href="{% url "core:home" %}">Nbnb</a>
    <ul>
        <li><a href="#">Login</a></li>
    </ul>
</header>

templates/partials/nav.html
<ul class="flex items-center text-sm font-medium h-full">
    {% if user.is_authenticated %}
        <li class="nav_link"><a href="{% url "users:logout" %}">Log out</a></li>
    {% else %}
        <li class="nav_link"><a href="{% url "users:login" %}">Login</a></li>
        <li class="nav_link"><a href="{% url "users:signup" %}">Sign up</a></li>
    {% endif %}
</u>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href="{% url 'users:github-login' %}" class="btn border-1 text-gray-700 border-gray-700 mb-3 bg-gray-400">
       <i class="fab fa-github"><span class="ml-3 fa-lg font-medium">Log in with Github</span></i> 
    </a>

    <a href="{% url 'users:kakao-login' %}" class="btn border-1 text-gray-700 border-yellow-700 mb-3 bg-yellow-400">
        <i class="fas fa-comment"><span class="ml-3 fa-lg font-medium">Log in with Kakao</span></i> 
    </a>
</div>

 <div class="flex items-center w-full my-5">
    <div class="h-px w-full bg-gray-500"></div>
    <span class="text-gray-700 font-medium text-sm mx-4">or</span>
    <div class="h-px w-full bg-gray-500"></div>
</div>