config/urls.py
from django.contrib import admin
from django.urls    import path, include
from django.conf    import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home")
]

rooms/urls.py
from django.urls import path
from rooms.views import RoomDetail, SearchView

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", RoomDetail.as_view(), name="detail"),
    path("search/", SearchView.as_view(), name="search")
]

templates/mixins/room_card.html
<div class="w-1/4 mb-10 px-2">
    <a href="{% url 'rooms:detail' room.pk %}">
        <div class ="w-full h-64 bg-cover bg-center rounded-lg mb-2" style="background-image: url({{room.first_photo}});"></div>
        <div class="flex justify-between mb-2">
            <div>
                {% if room.host.superhost %}
                    <span class="uppercase font-medium text-xs border border-black text-black rounded py-px px-1">Superhost</span>
                {% endif %}
                <span class="text-sm text-gray-600">{{room.city}}, {{room.country}}</span>
            </div>
            <span class="text-sm flex items-center">
                <i class="fas fa-star text-red-500 text-sm mr-px"></i>{{room.total_ratings}}
            </span>
        </div>
        <span class="text-black ">{{room.name}}</span>
    </a>
</div>


   